// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package collector

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadConnectProbe returns the embedded CollectionSpec for connectProbe.
func loadConnectProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ConnectProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load connectProbe: %w", err)
	}

	return spec, err
}

// loadConnectProbeObjects loads connectProbe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*connectProbeObjects
//	*connectProbePrograms
//	*connectProbeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadConnectProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadConnectProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// connectProbeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectProbeSpecs struct {
	connectProbeProgramSpecs
	connectProbeMapSpecs
}

// connectProbeSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectProbeProgramSpecs struct {
	TraceEnterConnect *ebpf.ProgramSpec `ebpf:"trace_enter_connect"`
}

// connectProbeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type connectProbeMapSpecs struct {
	ConnectEvents *ebpf.MapSpec `ebpf:"connect_events"`
}

// connectProbeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadConnectProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectProbeObjects struct {
	connectProbePrograms
	connectProbeMaps
}

func (o *connectProbeObjects) Close() error {
	return _ConnectProbeClose(
		&o.connectProbePrograms,
		&o.connectProbeMaps,
	)
}

// connectProbeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadConnectProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectProbeMaps struct {
	ConnectEvents *ebpf.Map `ebpf:"connect_events"`
}

func (m *connectProbeMaps) Close() error {
	return _ConnectProbeClose(
		m.ConnectEvents,
	)
}

// connectProbePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadConnectProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type connectProbePrograms struct {
	TraceEnterConnect *ebpf.Program `ebpf:"trace_enter_connect"`
}

func (p *connectProbePrograms) Close() error {
	return _ConnectProbeClose(
		p.TraceEnterConnect,
	)
}

func _ConnectProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed connectprobe_bpfeb.o
var _ConnectProbeBytes []byte
